SENDER        ?= 1
COLORS        ?= 1
VAAPI         ?= 1
NVENC_FFMPEG  ?= 1

ifeq ($(SENDER), 1)
SENDER_TARGET := $(BUILD_DIR)/$(SENDER_TARGET_NAME)
CFLAGS += -DFEATURE_SENDER
endif

ifeq ($(COLORS), 1)
CFLAGS += -DFEATURE_COLORS
endif

ifeq ($(VAAPI), 1)
CFLAGS += -DFEATURE_VAAPI
endif

ifeq ($(NVENC_FFMPEG), 1)
CFLAGS += -DFEATURE_NVENC_FFMPEG
endif
